# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
---
name: Windows tests

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  windows-test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -e '.[all]'
      - name: Source distribution test
        run: |
          python -m pip install --upgrade build
          python -m build --sdist
          pip install dist/chatarena-$(python -c "import chatarena; print(chatarena.__version__)").tar.gz
      - name: Release Test
        run: |
          pytest -v -n auto tests
